package com.skillbridge.entity.enums;

public enum JobCategory {
    EDUCATION, TECHNOLOGY, DESIGN, WRITING, TEACHING,
    LEGAL, FINANCE, MARKETING, MUSIC,
    PHOTOGRAPHY, VIDEO, TRANSLATION, CONSULTING
}
