package com.skillbridge.entity.enums;

public enum NotificationType {
    NEW_PROPOSAL, PROPOSAL_RECEIVED, PROPOSAL_ACCEPTED, PROPOSAL_REJECTED, PROPOSAL_UPDATE,
    PROJECT_COMPLETED, PROJECT_UPDATE, REVIEW_RECEIVED, MENTION,
    DISPUTE_RAISED, DISPUTE_RESOLVED, INACTIVITY_ALERT,
    JOB_EXPIRED, GENERAL, NEW_MESSAGE
}
