package com.skillbridge.entity.enums;

public enum NotificationType {
    PROPOSAL_RECEIVED, PROPOSAL_ACCEPTED, PROPOSAL_REJECTED,
    PROJECT_COMPLETED, REVIEW_RECEIVED, MENTION,
    DISPUTE_RAISED, DISPUTE_RESOLVED, INACTIVITY_ALERT,
    JOB_EXPIRED, GENERAL
}
